### PR TITLE
Multimax semantics fix

### LINKED ISSUE #142: Semantics of multimax differs from the original one
Cf. https://github.com/MLanguage/mlang/blob/51a2aaa37f7d1bd6fa757345bd647c0018a156c6/examples/dgfip_c/enchain_static.c#L186

Small changes wrt to when multimax returns a defined result.

### PR DESCRIPTION
**Pull request by Keryan-dev**
Closes #142 

`multimax` was though to be always defined, but it turns out it's only if any of its component is too.

Patched on top of #165 for simplicity, and silently dependent of #178.

### CODE REVIEW

File: src/mlang/backend_ir/bir_interpreter.ml [hunk 1]
```diff
@@ -571,6 +571,7 @@ module Make (N : Bir_number.NumberInterface) = struct
             in
             let maxi = ref (access_index 0) in
             for i = 0 to Int64.to_int up do
+              (* Fragile: rely on polymorphic compare where None < Some _ *)
```
Comment (denismerigoux) [inline src/mlang/backend_ir/bir_interpreter.ml:574]: Can you explicit this comparison with a match? This is the place where the reference semantics is so we want it to be very explicit.

**Review by denismerigoux — CHANGES_REQUESTED** [review]
So the fuzzed tests did not catch this semantic mismatch?

**Comment by Keryan-dev** [comment]
The fuzzing wouldn't be able to catch that, there is a single use of multimax in 2020 whose result is guarded by a casting operation.

**Review by denismerigoux — APPROVED** [review]
